hockeypuck/hockeypuck

- src/hockeypuck/conflux/recon/settings_test.go
Invalid port 'nope' seems to trigger a different error message in Go
1.12 on linux. Updated to use a numeric invalid port.
> Fix recon settings test.

- src/hockeypuck/hkp/handler.go
- src/hockeypuck/openpgp/resolve.go
- src/hockeypuck/openpgp/resolve_test.go
- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
These options prevent Hockeypuck from propagating keyring spam to GnuPG.
"Self-signed only" option removes all packets that are not "self-signed"
by the primary key.
"Fingerprint only" option only allows fingerprint and key ID queries --
no email addresses or name searches.
These options only affect queries; all uploaded key material is still
stored and synchronized with peers. They are not enabled by default.
> HKP query policy configuration options to protect gnupg.

- debian/control
- snapcraft.yaml
Not supporting other release architectures until there is demand for it.
> Remove unused release architectures from debian/control.

- README.md
- snap/hooks/configure
- src/hockeypuck/server/snap/hockeypuck-wrapper
This PR provides users with the ability to run the hockeypuck server with memory and cpu profiling via snap configuration options.
> Update hockeypuck wrapper to support cpu and memory profiling

- .travis.yml
- snapcraft.yaml
- src/hockeypuck/conflux/recon/gossip.go
- src/hockeypuck/conflux/recon/peer.go
- src/hockeypuck/conflux/recon/testing/runner.go
- src/hockeypuck/hkp/sks/recon.go
This avoids wasting unnecessary resources continuing to run
reconciliation while recovering missing keys.
> Block recon peer while recovering missing keys.

- contrib/pyinfra/base.py
- contrib/pyinfra/hockeypuck.conf
- contrib/pyinfra/hockeypuck.py
- contrib/pyinfra/lxd.py
- contrib/pyinfra/quick_backload.py
Need to separate out base installation steps to avoid operation
dependencies.
Add container name to host facts.
Add script to do a quick backload of 10 dump files for integration
testing.
Configure hockeypuck to drop keys > 1mb because it OOMs otherwise.
> Update deployment to pyinfra 1.2.

- src/hockeypuck/server/settings.go
Removed blacklist TODO, it'll only be used for primary keys.
> Default limits on packet length and overall key length.

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- contrib/docker-compose/devel/hockeypuck/bin/startup.sh
- contrib/docker-compose/devel/hockeypuck/etc/hockeypuck.conf
- docker-compose.yml
- src/hockeypuck/openpgp/subkey.go
- src/hockeypuck/openpgp/userid.go
- src/hockeypuck/openpgp/verify.go
While trying to document the steps I had to do for getting docker to run, I noticed that many things are more complicated than necessary:
- `2.1.0` and `master` would not build with docker (see #104)
- Loading a keydump was hard
- The usage of docker `ENTRYPOINT` made loading keys even harder
I also noticed that old system images (Ubuntu 18.04) and Go versions (mixture of 1.12/1.15(?)) were used and that the current build process would stop running on current Go (1.16). The copying of binaries from the `toolchain` looked fragile.
Here is version that simplifies and changes/fixes these things:
- Builds with docker again (fixes #104)
- Uses recent images (I noticed [`golang:buster`](https://hub.docker.com/_/golang?tab=tags&page=1&ordering=last_updated) and therefore started basing …
> Fix/improve docker support (and update environment)

- src/hockeypuck/go.mod
- src/hockeypuck/go.sum
- src/hockeypuck/hkp/sks/recon.go
Blacklisting keys and imposing packet/key size limits as done by Hockeypuck reduces the database size locally. However, these keys (typically of abusive length) will be re-requested on every reconciliation attempt, in vain. This causes a huge, unnecessary burden on those peers, possibly even resulting in denial of service. Sometimes, just requesting a chunk of these keys results in a timeout, due to the remote processing involved.
This PR addresses this in two ways:
I have had several requests fail (requesting many huge keys in one request, resulting in >30 s work at the other side and thus timeout) more or less continuously. This ensures that we are much more likely to make progress now, while trying to be nicer to our peers.
The request chunk size is adaptive between 10 and 100 (the …
> Reduce load on peers

- contrib/webroot/index.html
Forgot to remove the traces of my previous implementation from #about "modal dialog" that was abusing checkboxes. Doing it.
> Remove the traces of the my previous implementation.

- src/hockeypuck/server/server.go
Json and MR statistics use now numkeys instead of total and server_contact instead of contact. This changes make the statistics sks pool compatible
> updated server.go json stats numkeys and server_contact

- src/hockeypuck/hkp/handler.go
- src/hockeypuck/openpgp/io.go
- src/hockeypuck/openpgp/io_test.go
- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
Closes #83 
This PR will add `Comment` and `Version` headers in an armored OpenPGP key similar to the legacy SKS servers. Both values can be set by an optional TOML definition under OpenPGP:
```
[hockeypuck.openpgp.headers]
comment="Hostname: hkp.power.local"
version="Hockeypuck + SKS compatibility"
```
> Add OpenPGP headers support

- src/hockeypuck/conflux/recon/gossip.go
- src/hockeypuck/conflux/recon/settings.go
- src/hockeypuck/go.mod
- src/hockeypuck/go.sum
Allows tuning the probability of starting an (outgoing) gossip interaction with a peer. Instead of evenly distributing the load, now we have a weighted probability, controlled by the new `weight=<n>` option to `hockeypuck.conflux.recon.partner.*`.
The default weight is set at `100`; setting a weight to `-1` (or any negative value) will prevent the peer from being picked for outgoing gossip. (`0` would be the obvious choice, but unfortunately an explicity 0 cannot be distinguished from the absence of a `weight` parameter, AFAIK.)
Controlling the probability of incoming gossip requests is outside of the scope of this PR; options include blocking the peer or convincing its operator to apply a weight as well.
> Allow weighted peers

- src/hockeypuck/hkp/storage/mock/mock.go
- src/hockeypuck/hkp/storage/storage.go
- src/hockeypuck/pghkp/storage.go
- src/hockeypuck/server/cmd/hockeypuck-load/main.go
Fixes #131 
__ 9.5 - 10.5 hours, to load a complete key dump of ~6.13M keys (14GB)
[using Postgres DB config values:
wal_buffers = 16MB
checkpoint_timeout = 2min (this is the important one, I think)
checkpoint_flush_after = 16MB
Others left to defaults.]
__ Time breakdown per 15K-key file:
Sending keys to DB takes: 6.2 - 8.3 sec
Filtering & insertion takes: 43 - 50 sec
Measuring stats takes: 33.5 - 45 msec
Reading keys back takes: 13.5 - 50 sec
Total time per 15K-key file is ~1min 3sec -- ~1min 50sec.
__ Tried a type of "bulk-notify-listeners", which acquires the pghkp storage `mutex` only once for all notifications in a call to `Insert(..)`; this did not seem to change timing behavior, so it is commented-out in the code.
__ One-key-at-a-time insertion updated to merge keys with same …
> Bulk key insertion to Postgres DB

- src/hockeypuck/server/metrics.go
This will let us distinguish absurdly long-running requests from the merely astonishing.
> add buckets beyond 10s to http_request_duration_seconds

- contrib/docker-compose/standalone/hockeypuck/etc/hockeypuck.conf.tmpl
Use more sensible default in standalone hockeypuck config template
> Don't disable keyword search by default

- src/hockeypuck/hkp/handler.go
- src/hockeypuck/hkp/handler_test.go
- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
Trying to reduce the OOM kills that we get on our servers we would like to limit the number of keys returned based on memory usage. After we reach a certain threshold we would truncate the response and the rest of the requested keys can be requested on subsequent queries.
In our investigation, we discovered that POST requests to hashquery can result in multiple GB of memory being used to build a response and we aim to add a maximum response value configurable through a MaxResponseLen setting.
> Limit the output of the HashQuery response

- Makefile
- src/hockeypuck/conflux/bitstring_test.go
- src/hockeypuck/conflux/matrix_test.go
- src/hockeypuck/conflux/poly_test.go
- src/hockeypuck/conflux/recon/testing/run_splits.go
- src/hockeypuck/conflux/zp_test.go
- src/hockeypuck/go.mod
- src/hockeypuck/go.sum
- src/hockeypuck/hkp/requests.go
- src/hockeypuck/hkp/requests_test.go
- src/hockeypuck/openpgp/resolve_test.go
- src/hockeypuck/openpgp/types_test.go
Closes #169 
Also improved some of the tests:
* make had been consuming the stdout of `go fmt` so the error was uninformative
* c.Assert() expects its first argument to be the obtained string and the third the expected string. If these are reversed the error messages are confusing.
* [EDIT] x/sys required an update to run tests on my devel macbook
Currently deployed on https://fi.pgpkeys.eu
> Add support for 0x-free FP and long-ID index search #169

- contrib/docker-compose/standalone/README.md
- contrib/docker-compose/standalone/init-letsencrypt.bash
- contrib/docker-compose/standalone/mksite.bash
The SSL certificate for HTTPS is managed by certbot. The default
CA is Let's Encrypt, but some environments may not use it
(e.g. because they are not reachable from the public internet).
Thankfully, certbot implements a --server option to override the
default. Add support for this option to init-letsencrypt.bash and
add the ACME_SERVER variable to settings.
> docker-compose: Allow using a non-default CA

- Dockerfile
- Makefile
The `make lint` stage in the build workflow is causing issues with the gofmt 1.18->1.19 version bump (see #201). We should restrict `make lint` to the github PR workflow, as linting is only of interest to developers.
> Remove lint from default build workflow

- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
this adds a new configuration parameter to enable/disable the request
details
the default is the previous behaviour
addresses hockeypuck/hockeypuck#193
> optionally remove remote address and user agent from logs

- src/hockeypuck/server/cmd/cmd.go
- src/hockeypuck/server/cmd/hockeypuck-dump/main.go
- src/hockeypuck/server/cmd/hockeypuck-load/main.go
- src/hockeypuck/server/cmd/hockeypuck-pbuild/main.go
- src/hockeypuck/server/cmd/hockeypuck/main.go
when any of the fours command is called without -config parameter, the output
is currently:
```
open : no such file or directory
main.main
/var/lib/hockeypuck/hockeypuck/src/hockeypuck/server/cmd/hockeypuck-pbuild/main.go:36
runtime.main
/opt/go/1.19/src/runtime/proc.go:250
runtime.goexit
```
which does not say what the error actually is. Except when looking into the code.
Therefore, output additional messages:
if loading the configuration file itself fails
or if parsing the configuration file fails
Now the commands also say:
```
Error loading configuration file ''.
```
That at least gives a hint what the error is about, namely the config file. A default config path would be nice too ;)
> proper error messages for config load fail

- debian/hockeypuck.service
Use loose coupling of postgresql.service to allow deployment of Hockeypuck and a database on separate hosts. Restart automatically the service on failure in case for example postgresql.service takes longer to boot.
Closes #222
> CHORE: Update systemd service settings

- src/hockeypuck/hkp/handler.go
- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
We want to let Hockeypuck server pick the request Host header and use it for presenting stats and other information using it. This way we can expose the service via Tor for example.
Closes #231
> Add server vhosts support

- contrib/docker-compose/standalone/docker-compose-shim.yml
We want to be able to configure FQDN aliases for Hockeypuck that HAProxy shim will handle.
> CHORE: Add ALIAS_FQDNS and CLUSTER_FQDNS variables for Docker shim

- contrib/docker-compose/standalone/haproxy/etc/haproxy.d/50_fe_http_handler.cfg
It looks like that HAProxy documentation is misleading and .if-.elseif-.endif is not a correct construct. This change splits it into two separate .if-.endif
> HOTFIX: Fix if-else logic in 50_fe_http_handler.conf

- README.md
- src/hockeypuck/server/settings.go
Rename the custom `env` templating function to `osenv` and make it filter OS environment variables based of prefix.
> CHORE: Rename custom env templating function to osenv

- .github/workflows/label-pull-requests.yml
- .github/workflows/update-release-draft.yml
Now that the configuration files for the workflows are available, we want to add the actions too.
Closes #233
> Extend GH workflows for release notes and PR labellers

- contrib/templates/stats.html.tmpl
Hello, I was missing a "Return" button to return to the home page
Here my suggestion
Close: #326
> [FEATURE] Add return button to stats page

- CONTRIBUTORS
- contrib/templates/stats.html.tmpl
- contrib/webroot/index.html
- src/hockeypuck/conflux/recon/gossip.go
- src/hockeypuck/conflux/recon/peer.go
- src/hockeypuck/conflux/recon/peer_test.go
- src/hockeypuck/conflux/recon/settings.go
- src/hockeypuck/conflux/recon/settings_test.go
- src/hockeypuck/hkp/sks/recon.go
- src/hockeypuck/server/server.go
- src/hockeypuck/server/settings.go
Significant refactoring of conflux to use Partner structs as the basic unit of information. IPMatcher and Recover now handle *Partner references instead of net.Addrs, meaning that:
* We can store remote IPs for matching (all of them! #258) in Partner structs
* ... and keep them updated as remote IP addresses change over time
* So we can return the matching Partner from Match() instead of a boolean
* Meaning the Host: header is now set correctly in outgoing hashqueries #292
* Logs are more informative
* Most recent sync state of each partner can be displayed in stats
As part of this refactoring, RandomPartner has been moved into IPMatcher, and IPMatcher is a static member of Peer, rather than a scope variable in (*Peer)Serve(). This is necessary because Settings contains a hash of Partner …
> [FEATURE] handle Partner structs internally instead of ip addresses (closes #292 #258 #98)

- contrib/data-sources.md
The previous link to the data sources seems to have been moved. I have updated the links to point to the right URLs.
> Update data-sources.md to point to the right link

- contrib/docker-compose/standalone/sync-sks-dump.bash
- `sync-sks-dump.bash` was failing due to invalid link in the script, fixed that.
- The `docker-compose.yml` has the hockeypuck container with the volume pointing to `/hockeypuck/import/` whereas the `startup.sh` script invoked by it has the `keydump` variable pointing to `$hkp/import/dump`. Because of this, it fails to start up the container with the error `no keydump available` even though keydump is present.
> Update standalone deployment of hockeypuck

- contrib/templates/stats.html.tmpl
- src/hockeypuck/conflux/recon/settings.go
- src/hockeypuck/server/server.go
Add some new configurable variables to the stats page.
In the `hockeypuck.conflux.recon.partner` list, for each partner peer, these variables are added:
- `webAddr` (string): The domain / hostname to display on stats page. By default we use `example.com:11371`, for servers that have a reverse proxy or load balancer the default HTTP/HTTPS port could be used (so no port need to be specified) or a different domain may be used. This is also useful for some browsers and firewalls that only permit user to request HTTP services on common ports.
- `statsPath` (string): The endpoint of stats page of the peer server, current default is `/pks/lookup?op=stats`. The `statsPath` key is also added to `mr` output. Close #370 
- `mask` (boolean): If set `true`, the HTTP and Recon address displayed in …
> Add some configurable variables to stats page
