hockeypuck/hockeypuck

contrib/webroot/404.html, contrib/webroot/index.html
=> Remove contact section.

contrib/pyinfra/.gitignore, contrib/pyinfra/README.md, contrib/pyinfra/example.py, contrib/pyinfra/hockeypuck.conf, contrib/pyinfra/hockeypuck.py, contrib/pyinfra/lxd.py
Stacked on top of #81 because this is my hammer for integration testing that PR...
=> Add pyinfra deployment.

contrib/pyinfra/google.tf
Remove unused volume, increase root disk to 100GB.
=> Fix terraform google deployment.

.dockerignore, Dockerfile, docker-compose.yml
Update docker build to work with recent changes. Fixes #95.
=> Fix docker build.

contrib/templates/index.html.tmpl
Fixes #100. Tweak template whitespace a bit.
=> Show primary key self-signatures in web UI.

contrib/docker-compose/standalone/docker-compose.yml, contrib/docker-compose/standalone/hockeypuck/etc/hockeypuck.conf.tmpl
Update standalone/docker-compose.yml to track changes in other docker-compose configs
=> Standalone consistency

debian/control, src/hockeypuck/hkp/sks/recon.go, src/hockeypuck/hkp/sks/recon_test.go, src/hockeypuck/server/server.go
=> Set User-agent to Software/Version

src/hockeypuck/server/server.go
=> Add Server response header

.github/workflows/docker-publish.yml
The change in newer docker registry so we can pull the image down without issues
=> Change from old docker.pkg.github.com to the new ghcr.io

src/hockeypuck/hkp/sks/recon.go
There is an unused parameter `maxKeyRecoveryAttempts` defined in src/hockeypuck/hkp/sks/recon.go . Let's return failure quickly once the chunk request error count exceeds it. Also sleep for 1s after each chunk failure, to avoid hammering a server when it's already struggling.
=> Fail more gracefully during chunk recovery #126 #166

contrib/docker-compose/standalone/README.md, contrib/docker-compose/standalone/delete-keys.bash
Also updated standalone README for clarity
=> Add key deletion helper script

src/hockeypuck/openpgp/resolve.go
=> Process UID and UAT revocations the same as subkey revocations

README.md
and mention make for building and installing
=> readme: name build commands explicitly

contrib/templates/stats.html.tmpl
so referencing sections is available
=> stats template: add ids to headers

README.md
I wrote an ansible role for easily deploying hockeypuck servers.
Maybe it is useful for others as well.
=> Readme: add ansible role

contrib/docker-compose/standalone/hockeypuck/etc/hockeypuck.conf.tmpl
set logRequestDetails to false as suggested in hockeypuck/hockeypuck#193
=> standalone default config: disable logRequestDetails

src/hockeypuck/conflux/recon/settings.go, src/hockeypuck/conflux/recon/settings_test.go, src/hockeypuck/hkp/sks/recon.go
LRU seen cache size is hard-coded at the moment and cannot be changed from the settings file. We want to make it configurable.
Closes #225
=> CHORE: Allow seenCacheSize to be set from config

contrib/docker-compose/standalone/hockeypuck/etc/hockeypuck.conf.tmpl, contrib/templates/index.html.tmpl, src/hockeypuck/hkp/handler.go, src/hockeypuck/hkp/handler_test.go, src/hockeypuck/openpgp/selfsigs.go, src/hockeypuck/pghkp/storage.go
Closes #194
Closes #196
Closes #197
=> Multiple fixes

contrib/docker-compose/standalone/haproxy-entrypoint.sh
We want the container to exit when haproxy dies
=> Container should exit when haproxy does

src/hockeypuck/hkp/handler.go, src/hockeypuck/openpgp/io.go, src/hockeypuck/openpgp/pubkey.go
We want to move some log messages to DEBUG level and extend the list of algorithm methods.
=> Various log level changes and extensive algo names

contrib/docker-compose/standalone/haproxy/etc/haproxy.d/50_fe_http_handler.cfg
Use correct syntax for the .if-.elif-.endif construct
=> CHORE: Restore the logic in 50_fe_http_handler

contrib/docker-compose/standalone/init-letsencrypt.bash
=> Fix unset variables in ACME config

contrib/docker-compose/standalone/README.md, contrib/docker-compose/standalone/clean-images.bash, contrib/docker-compose/standalone/docker-compose.yml, contrib/docker-compose/standalone/haproxy/etc/haproxy.d/50_fe_http_handler.cfg, contrib/docker-compose/standalone/haproxy/etc/haproxy.d/README.md, contrib/docker-compose/standalone/hockeypuck-entrypoint.sh, contrib/docker-compose/standalone/hockeypuck/etc/README.md, contrib/docker-compose/standalone/hockeypuck/etc/hockeypuck.conf.tmpl, contrib/docker-compose/standalone/mkconfig.bash, contrib/docker-compose/standalone/mksite.bash
* Use Go text/template in the configuration file for docker-compose/standalone.
* Improve HSTS handling in HAproxy
=> Parameterise standalone

src/hockeypuck/conflux/recon/peer.go, src/hockeypuck/hkp/sks/recon.go, src/hockeypuck/hkp/sks/stats.go, src/hockeypuck/hkp/storage/storage.go, src/hockeypuck/pghkp/storage.go, src/hockeypuck/server/metrics.go
=> Cleanup PTree drift

src/hockeypuck/hkp/handler.go, src/hockeypuck/hkp/handler_test.go
... also adds a (trivial) test handler for stats
=> also serve stats on /pks/stats (closes #356); DRIVEBY add static /pks/health endpoint

.github/workflows/docker-publish.yml
Use docker build github action to publish multi-arch docker image
Fixes #374
=> Build multi-archi docker image

src/hockeypuck/hkp/handler.go
In several places, Handler returns excessively severe HTTP errors. We should try to align with the following:
* Certificate bundle is parseable but unverifiable (e.g. bad sigs): Ignored
* HTTP request is parseable but bundle is not: Unprocessable Entity
* HTTP request is not parseable: Bad Request
* Back end threw unexpected error: Internal Server Error
The first of the above should mean that unknown versions or algorithms will be gracefully ignored rather than throw an HTTP error.
=> Reduce severity of many errors
